version: "3.9"
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind_psql/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
